export * from "./create-presentation";
export * from "./create-slide";
export * from "./delete-presentation";
export * from "./delete-slide";
export * from "./edit-presentation";
export * from "./edit-slide";
export * from "./list-presentation";
export * from "./list-slide";
export * from "./start-presentation";
